$schema: https://json.schemastore.org/package
version: 0.0.0
name: pre-package

type: module
main: ./lib/pnpmfile.cjs
exports:
  ./read: ./lib/read.js

engines:
  node: ">=18"
  pnpm: ">=8"
packageManager: pnpm@8.15.1

dependencies:
  fast-glob: ^3.3.2
  node-cleanup: ^2.1.2
  yaml: ^2.3.4

devDependencies:
  "@danielx/civet": ^0.6.64
  "@rollup/plugin-strip": ^3.0.4
  rollup-plugin-cleanup: ^3.2.1
  rollup-plugin-prettier: ^4.1.1
  rollup-plugin-tla: ^0.0.2
  rollup: ^4.9.4

prettier: "@danielbayley/prettier-config"

scripts:
  build: rollup --configPlugin @danielx/civet/rollup --config rollup.civet
